[install.scopes]
"@factorywager" = { token = "$FW_REGISTRY_TOKEN", url = "https://registry.npmjs.org/" }
"@duoplus" = { token = "$FW_REGISTRY_TOKEN", url = "https://registry.npmjs.org/" }

[install]
exact = true
registry = "https://registry.npmjs.org"

[publish]
registry = "https://registry.npmjs.org"
