{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "quantum-hash-service",
    "labels": {
      "app": "quantum-hash"
    }
  },
  "spec": {
    "selector": {
      "app": "quantum-hash"
    },
    "ports": [
      {
        "port": 80,
        "targetPort": 3000,
        "protocol": "TCP"
      }
    ],
    "type": "ClusterIP"
  }
}